### ISSUE TITLE
Graphic design for cat grave

### ISSUE THREAD

**Issue by pepellou** [pepellou/nosediceasi#4]
I imagine the graves arranged in rows of N graves.
It does not really matter what N is, so the size of the graves is up to you (being you the assignee of this issue 😬 ).

**Comment by pepellou** [comment]
@CoolLawyer how can I help? .... drawing??

**Comment by CoolLawyer** [comment]
![cat grave](https://user-images.githubusercontent.com/26244782/28832435-b1992fc6-76dc-11e7-9af2-813b6755e886.png)

**Comment by kuartillo** [comment]
🗡
